/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'defaultStatsView' : { 'monthly' : null } |
    { 'daily' : null } |
    { 'weekly' : null },
  'impactGoal' : number,
  'notificationLeadTime' : bigint,
  'pauseTimers' : boolean,
  'completionGoal' : bigint,
  'darkMode' : boolean,
  'defaultHabitsView' : { 'monthly' : null } |
    { 'daily' : null } |
    { 'weekly' : null },
  'confirmDelete' : boolean,
  'mondayFirst' : boolean,
}
export interface Group { 'id' : string, 'name' : string, 'color' : string }
export interface Habit {
  'id' : string,
  'startTime' : string,
  'repeatType' : { 'onetime' : null } |
    { 'daily' : null },
  'graceEnabled' : boolean,
  'timerDuration' : bigint,
  'weekdays' : Array<bigint>,
  'icon' : string,
  'mode' : { 'timer' : null } |
    { 'normal' : null },
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
  'hidden' : boolean,
  'importance' : bigint,
  'gracePeriod' : bigint,
  'dueTime' : string,
  'groupId' : [] | [string],
}
export interface HabitLog {
  'id' : string,
  'status' : { 'ontime' : null } |
    { 'late' : null } |
    { 'failed' : null },
  'completedAt' : bigint,
  'date' : string,
  'habitId' : string,
  'pointsEarned' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string, string, string], undefined>,
  'createHabit' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      { 'timer' : null } |
        { 'normal' : null },
      bigint,
      string,
      string,
      boolean,
      bigint,
      { 'onetime' : null } |
        { 'daily' : null },
      Array<bigint>,
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'deleteGroup' : ActorMethod<[string], undefined>,
  'deleteHabit' : ActorMethod<[string], undefined>,
  'deleteLogsByRange' : ActorMethod<
    [
      { 'day' : string } |
        { 'month' : string } |
        { 'week' : string } |
        { 'alltime' : null },
    ],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyCompletionHistory' : ActorMethod<
    [string, string],
    Array<[string, bigint, number]>
  >,
  'getGroups' : ActorMethod<[], Array<Group>>,
  'getHabit' : ActorMethod<[string], Habit>,
  'getHabitStats' : ActorMethod<
    [string],
    {
      'streak' : bigint,
      'failedCount' : bigint,
      'completionCount' : bigint,
      'totalPoints' : number,
      'lateCount' : bigint,
    }
  >,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getLogsByDateRange' : ActorMethod<[string, string], Array<HabitLog>>,
  'getLogsByHabit' : ActorMethod<[string], Array<HabitLog>>,
  'getOverviewStats' : ActorMethod<
    [string, string],
    {
      'failedCount' : bigint,
      'onTimeCount' : bigint,
      'maxPoints' : number,
      'totalCompletions' : bigint,
      'totalPoints' : number,
      'lateCount' : bigint,
    }
  >,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logHabitCompletion' : ActorMethod<
    [
      string,
      string,
      string,
      { 'ontime' : null } |
        { 'late' : null } |
        { 'failed' : null },
      bigint,
      number,
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGroup' : ActorMethod<[string, string, string], undefined>,
  'updateHabit' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      { 'timer' : null } |
        { 'normal' : null },
      bigint,
      string,
      string,
      boolean,
      bigint,
      { 'onetime' : null } |
        { 'daily' : null },
      Array<bigint>,
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];