/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Group = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const Habit = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Text,
  'repeatType' : IDL.Variant({ 'onetime' : IDL.Null, 'daily' : IDL.Null }),
  'graceEnabled' : IDL.Bool,
  'timerDuration' : IDL.Nat,
  'weekdays' : IDL.Vec(IDL.Nat),
  'icon' : IDL.Text,
  'mode' : IDL.Variant({ 'timer' : IDL.Null, 'normal' : IDL.Null }),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'hidden' : IDL.Bool,
  'importance' : IDL.Nat,
  'gracePeriod' : IDL.Nat,
  'dueTime' : IDL.Text,
  'groupId' : IDL.Opt(IDL.Text),
});
export const HabitLog = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'ontime' : IDL.Null,
    'late' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'completedAt' : IDL.Int,
  'date' : IDL.Text,
  'habitId' : IDL.Text,
  'pointsEarned' : IDL.Float64,
});
export const AppSettings = IDL.Record({
  'defaultStatsView' : IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  }),
  'impactGoal' : IDL.Float64,
  'notificationLeadTime' : IDL.Nat,
  'pauseTimers' : IDL.Bool,
  'completionGoal' : IDL.Nat,
  'darkMode' : IDL.Bool,
  'defaultHabitsView' : IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  }),
  'confirmDelete' : IDL.Bool,
  'mondayFirst' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createHabit' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({ 'timer' : IDL.Null, 'normal' : IDL.Null }),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Variant({ 'onetime' : IDL.Null, 'daily' : IDL.Null }),
        IDL.Vec(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'deleteGroup' : IDL.Func([IDL.Text], [], []),
  'deleteHabit' : IDL.Func([IDL.Text], [], []),
  'deleteLogsByRange' : IDL.Func(
      [
        IDL.Variant({
          'day' : IDL.Text,
          'month' : IDL.Text,
          'week' : IDL.Text,
          'alltime' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyCompletionHistory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getHabit' : IDL.Func([IDL.Text], [Habit], ['query']),
  'getHabitStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'streak' : IDL.Nat,
          'failedCount' : IDL.Nat,
          'completionCount' : IDL.Nat,
          'totalPoints' : IDL.Float64,
          'lateCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getLogsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(HabitLog)],
      ['query'],
    ),
  'getLogsByHabit' : IDL.Func([IDL.Text], [IDL.Vec(HabitLog)], ['query']),
  'getOverviewStats' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'failedCount' : IDL.Nat,
          'onTimeCount' : IDL.Nat,
          'maxPoints' : IDL.Float64,
          'totalCompletions' : IDL.Nat,
          'totalPoints' : IDL.Float64,
          'lateCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logHabitCompletion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'ontime' : IDL.Null,
          'late' : IDL.Null,
          'failed' : IDL.Null,
        }),
        IDL.Int,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateHabit' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({ 'timer' : IDL.Null, 'normal' : IDL.Null }),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Variant({ 'onetime' : IDL.Null, 'daily' : IDL.Null }),
        IDL.Vec(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateSettings' : IDL.Func([AppSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Group = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const Habit = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Text,
    'repeatType' : IDL.Variant({ 'onetime' : IDL.Null, 'daily' : IDL.Null }),
    'graceEnabled' : IDL.Bool,
    'timerDuration' : IDL.Nat,
    'weekdays' : IDL.Vec(IDL.Nat),
    'icon' : IDL.Text,
    'mode' : IDL.Variant({ 'timer' : IDL.Null, 'normal' : IDL.Null }),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'hidden' : IDL.Bool,
    'importance' : IDL.Nat,
    'gracePeriod' : IDL.Nat,
    'dueTime' : IDL.Text,
    'groupId' : IDL.Opt(IDL.Text),
  });
  const HabitLog = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'ontime' : IDL.Null,
      'late' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'completedAt' : IDL.Int,
    'date' : IDL.Text,
    'habitId' : IDL.Text,
    'pointsEarned' : IDL.Float64,
  });
  const AppSettings = IDL.Record({
    'defaultStatsView' : IDL.Variant({
      'monthly' : IDL.Null,
      'daily' : IDL.Null,
      'weekly' : IDL.Null,
    }),
    'impactGoal' : IDL.Float64,
    'notificationLeadTime' : IDL.Nat,
    'pauseTimers' : IDL.Bool,
    'completionGoal' : IDL.Nat,
    'darkMode' : IDL.Bool,
    'defaultHabitsView' : IDL.Variant({
      'monthly' : IDL.Null,
      'daily' : IDL.Null,
      'weekly' : IDL.Null,
    }),
    'confirmDelete' : IDL.Bool,
    'mondayFirst' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createHabit' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({ 'timer' : IDL.Null, 'normal' : IDL.Null }),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Variant({ 'onetime' : IDL.Null, 'daily' : IDL.Null }),
          IDL.Vec(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'deleteGroup' : IDL.Func([IDL.Text], [], []),
    'deleteHabit' : IDL.Func([IDL.Text], [], []),
    'deleteLogsByRange' : IDL.Func(
        [
          IDL.Variant({
            'day' : IDL.Text,
            'month' : IDL.Text,
            'week' : IDL.Text,
            'alltime' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyCompletionHistory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getHabit' : IDL.Func([IDL.Text], [Habit], ['query']),
    'getHabitStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'streak' : IDL.Nat,
            'failedCount' : IDL.Nat,
            'completionCount' : IDL.Nat,
            'totalPoints' : IDL.Float64,
            'lateCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getLogsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(HabitLog)],
        ['query'],
      ),
    'getLogsByHabit' : IDL.Func([IDL.Text], [IDL.Vec(HabitLog)], ['query']),
    'getOverviewStats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'failedCount' : IDL.Nat,
            'onTimeCount' : IDL.Nat,
            'maxPoints' : IDL.Float64,
            'totalCompletions' : IDL.Nat,
            'totalPoints' : IDL.Float64,
            'lateCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logHabitCompletion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'ontime' : IDL.Null,
            'late' : IDL.Null,
            'failed' : IDL.Null,
          }),
          IDL.Int,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateHabit' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({ 'timer' : IDL.Null, 'normal' : IDL.Null }),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Variant({ 'onetime' : IDL.Null, 'daily' : IDL.Null }),
          IDL.Vec(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateSettings' : IDL.Func([AppSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };