/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Habit {
    id: string;
    startTime: string;
    repeatType: Variant_onetime_daily;
    graceEnabled: boolean;
    timerDuration: bigint;
    weekdays: Array<bigint>;
    icon: string;
    mode: Variant_timer_normal;
    name: string;
    createdAt: bigint;
    color: string;
    hidden: boolean;
    importance: bigint;
    gracePeriod: bigint;
    dueTime: string;
    groupId?: string;
}
export interface HabitLog {
    id: string;
    status: Variant_ontime_late_failed;
    completedAt: bigint;
    date: string;
    habitId: string;
    pointsEarned: number;
}
export interface Group {
    id: string;
    name: string;
    color: string;
}
export interface UserProfile {
    name: string;
}
export interface AppSettings {
    defaultStatsView: Variant_monthly_daily_weekly;
    impactGoal: number;
    notificationLeadTime: bigint;
    pauseTimers: boolean;
    completionGoal: bigint;
    darkMode: boolean;
    defaultHabitsView: Variant_monthly_daily_weekly;
    confirmDelete: boolean;
    mondayFirst: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_monthly_daily_weekly {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum Variant_onetime_daily {
    onetime = "onetime",
    daily = "daily"
}
export enum Variant_ontime_late_failed {
    ontime = "ontime",
    late = "late",
    failed = "failed"
}
export enum Variant_timer_normal {
    timer = "timer",
    normal = "normal"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGroup(id: string, name: string, color: string): Promise<void>;
    createHabit(id: string, name: string, color: string, icon: string, importance: bigint, mode: Variant_timer_normal, timerDuration: bigint, startTime: string, dueTime: string, graceEnabled: boolean, gracePeriod: bigint, repeatType: Variant_onetime_daily, weekdays: Array<bigint>, groupId: string | null, hidden: boolean): Promise<void>;
    deleteGroup(id: string): Promise<void>;
    deleteHabit(id: string): Promise<void>;
    deleteLogsByRange(rangeType: {
        __kind__: "day";
        day: string;
    } | {
        __kind__: "month";
        month: string;
    } | {
        __kind__: "week";
        week: string;
    } | {
        __kind__: "alltime";
        alltime: null;
    }): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyCompletionHistory(startDate: string, endDate: string): Promise<Array<[string, bigint, number]>>;
    getGroups(): Promise<Array<Group>>;
    getHabit(id: string): Promise<Habit>;
    getHabitStats(habitId: string): Promise<{
        streak: bigint;
        failedCount: bigint;
        completionCount: bigint;
        totalPoints: number;
        lateCount: bigint;
    }>;
    getHabits(): Promise<Array<Habit>>;
    getLogsByDateRange(startDate: string, endDate: string): Promise<Array<HabitLog>>;
    getLogsByHabit(habitId: string): Promise<Array<HabitLog>>;
    getOverviewStats(_startDate: string, _endDate: string): Promise<{
        failedCount: bigint;
        onTimeCount: bigint;
        maxPoints: number;
        totalCompletions: bigint;
        totalPoints: number;
        lateCount: bigint;
    }>;
    getSettings(): Promise<AppSettings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logHabitCompletion(id: string, habitId: string, date: string, status: Variant_ontime_late_failed, completedAt: bigint, pointsEarned: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateGroup(id: string, name: string, color: string): Promise<void>;
    updateHabit(id: string, name: string, color: string, icon: string, importance: bigint, mode: Variant_timer_normal, timerDuration: bigint, startTime: string, dueTime: string, graceEnabled: boolean, gracePeriod: bigint, repeatType: Variant_onetime_daily, weekdays: Array<bigint>, groupId: string | null, hidden: boolean): Promise<void>;
    updateSettings(newSettings: AppSettings): Promise<void>;
}
import type { AppSettings as _AppSettings, Habit as _Habit, HabitLog as _HabitLog, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGroup(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1, arg2);
            return result;
        }
    }
    async createHabit(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Variant_timer_normal, arg6: bigint, arg7: string, arg8: string, arg9: boolean, arg10: bigint, arg11: Variant_onetime_daily, arg12: Array<bigint>, arg13: string | null, arg14: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg13), arg14);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg13), arg14);
            return result;
        }
    }
    async deleteGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async deleteHabit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteLogsByRange(arg0: {
        __kind__: "day";
        day: string;
    } | {
        __kind__: "month";
        month: string;
    } | {
        __kind__: "week";
        week: string;
    } | {
        __kind__: "alltime";
        alltime: null;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLogsByRange(to_candid_variant_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLogsByRange(to_candid_variant_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyCompletionHistory(arg0: string, arg1: string): Promise<Array<[string, bigint, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyCompletionHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyCompletionHistory(arg0, arg1);
            return result;
        }
    }
    async getGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroups();
            return result;
        }
    }
    async getHabit(arg0: string): Promise<Habit> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabit(arg0);
                return from_candid_Habit_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabit(arg0);
            return from_candid_Habit_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabitStats(arg0: string): Promise<{
        streak: bigint;
        failedCount: bigint;
        completionCount: bigint;
        totalPoints: number;
        lateCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitStats(arg0);
            return result;
        }
    }
    async getHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogsByDateRange(arg0: string, arg1: string): Promise<Array<HabitLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogsByDateRange(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogsByDateRange(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogsByHabit(arg0: string): Promise<Array<HabitLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogsByHabit(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogsByHabit(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverviewStats(arg0: string, arg1: string): Promise<{
        failedCount: bigint;
        onTimeCount: bigint;
        maxPoints: number;
        totalCompletions: bigint;
        totalPoints: number;
        lateCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverviewStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverviewStats(arg0, arg1);
            return result;
        }
    }
    async getSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_AppSettings_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_AppSettings_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logHabitCompletion(arg0: string, arg1: string, arg2: string, arg3: Variant_ontime_late_failed, arg4: bigint, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logHabitCompletion(arg0, arg1, arg2, to_candid_variant_n23(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logHabitCompletion(arg0, arg1, arg2, to_candid_variant_n23(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateGroup(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroup(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroup(arg0, arg1, arg2);
            return result;
        }
    }
    async updateHabit(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Variant_timer_normal, arg6: bigint, arg7: string, arg8: string, arg9: boolean, arg10: bigint, arg11: Variant_onetime_daily, arg12: Array<bigint>, arg13: string | null, arg14: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabit(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg13), arg14);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabit(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, to_candid_variant_n4(this._uploadFile, this._downloadFile, arg11), arg12, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg13), arg14);
            return result;
        }
    }
    async updateSettings(arg0: AppSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_AppSettings_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_AppSettings_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppSettings_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppSettings): AppSettings {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_HabitLog_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitLog): HabitLog {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Habit_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Habit): Habit {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: string;
    repeatType: {
        onetime: null;
    } | {
        daily: null;
    };
    graceEnabled: boolean;
    timerDuration: bigint;
    weekdays: Array<bigint>;
    icon: string;
    mode: {
        timer: null;
    } | {
        normal: null;
    };
    name: string;
    createdAt: bigint;
    color: string;
    hidden: boolean;
    importance: bigint;
    gracePeriod: bigint;
    dueTime: string;
    groupId: [] | [string];
}): {
    id: string;
    startTime: string;
    repeatType: Variant_onetime_daily;
    graceEnabled: boolean;
    timerDuration: bigint;
    weekdays: Array<bigint>;
    icon: string;
    mode: Variant_timer_normal;
    name: string;
    createdAt: bigint;
    color: string;
    hidden: boolean;
    importance: bigint;
    gracePeriod: bigint;
    dueTime: string;
    groupId?: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        repeatType: from_candid_variant_n12(_uploadFile, _downloadFile, value.repeatType),
        graceEnabled: value.graceEnabled,
        timerDuration: value.timerDuration,
        weekdays: value.weekdays,
        icon: value.icon,
        mode: from_candid_variant_n13(_uploadFile, _downloadFile, value.mode),
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        hidden: value.hidden,
        importance: value.importance,
        gracePeriod: value.gracePeriod,
        dueTime: value.dueTime,
        groupId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.groupId))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        ontime: null;
    } | {
        late: null;
    } | {
        failed: null;
    };
    completedAt: bigint;
    date: string;
    habitId: string;
    pointsEarned: number;
}): {
    id: string;
    status: Variant_ontime_late_failed;
    completedAt: bigint;
    date: string;
    habitId: string;
    pointsEarned: number;
} {
    return {
        id: value.id,
        status: from_candid_variant_n19(_uploadFile, _downloadFile, value.status),
        completedAt: value.completedAt,
        date: value.date,
        habitId: value.habitId,
        pointsEarned: value.pointsEarned
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defaultStatsView: {
        monthly: null;
    } | {
        daily: null;
    } | {
        weekly: null;
    };
    impactGoal: number;
    notificationLeadTime: bigint;
    pauseTimers: boolean;
    completionGoal: bigint;
    darkMode: boolean;
    defaultHabitsView: {
        monthly: null;
    } | {
        daily: null;
    } | {
        weekly: null;
    };
    confirmDelete: boolean;
    mondayFirst: boolean;
}): {
    defaultStatsView: Variant_monthly_daily_weekly;
    impactGoal: number;
    notificationLeadTime: bigint;
    pauseTimers: boolean;
    completionGoal: bigint;
    darkMode: boolean;
    defaultHabitsView: Variant_monthly_daily_weekly;
    confirmDelete: boolean;
    mondayFirst: boolean;
} {
    return {
        defaultStatsView: from_candid_variant_n22(_uploadFile, _downloadFile, value.defaultStatsView),
        impactGoal: value.impactGoal,
        notificationLeadTime: value.notificationLeadTime,
        pauseTimers: value.pauseTimers,
        completionGoal: value.completionGoal,
        darkMode: value.darkMode,
        defaultHabitsView: from_candid_variant_n22(_uploadFile, _downloadFile, value.defaultHabitsView),
        confirmDelete: value.confirmDelete,
        mondayFirst: value.mondayFirst
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onetime: null;
} | {
    daily: null;
}): Variant_onetime_daily {
    return "onetime" in value ? Variant_onetime_daily.onetime : "daily" in value ? Variant_onetime_daily.daily : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timer: null;
} | {
    normal: null;
}): Variant_timer_normal {
    return "timer" in value ? Variant_timer_normal.timer : "normal" in value ? Variant_timer_normal.normal : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ontime: null;
} | {
    late: null;
} | {
    failed: null;
}): Variant_ontime_late_failed {
    return "ontime" in value ? Variant_ontime_late_failed.ontime : "late" in value ? Variant_ontime_late_failed.late : "failed" in value ? Variant_ontime_late_failed.failed : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): Variant_monthly_daily_weekly {
    return "monthly" in value ? Variant_monthly_daily_weekly.monthly : "daily" in value ? Variant_monthly_daily_weekly.daily : "weekly" in value ? Variant_monthly_daily_weekly.weekly : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Habit>): Array<Habit> {
    return value.map((x)=>from_candid_Habit_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HabitLog>): Array<HabitLog> {
    return value.map((x)=>from_candid_HabitLog_n17(_uploadFile, _downloadFile, x));
}
function to_candid_AppSettings_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppSettings): _AppSettings {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defaultStatsView: Variant_monthly_daily_weekly;
    impactGoal: number;
    notificationLeadTime: bigint;
    pauseTimers: boolean;
    completionGoal: bigint;
    darkMode: boolean;
    defaultHabitsView: Variant_monthly_daily_weekly;
    confirmDelete: boolean;
    mondayFirst: boolean;
}): {
    defaultStatsView: {
        monthly: null;
    } | {
        daily: null;
    } | {
        weekly: null;
    };
    impactGoal: number;
    notificationLeadTime: bigint;
    pauseTimers: boolean;
    completionGoal: bigint;
    darkMode: boolean;
    defaultHabitsView: {
        monthly: null;
    } | {
        daily: null;
    } | {
        weekly: null;
    };
    confirmDelete: boolean;
    mondayFirst: boolean;
} {
    return {
        defaultStatsView: to_candid_variant_n26(_uploadFile, _downloadFile, value.defaultStatsView),
        impactGoal: value.impactGoal,
        notificationLeadTime: value.notificationLeadTime,
        pauseTimers: value.pauseTimers,
        completionGoal: value.completionGoal,
        darkMode: value.darkMode,
        defaultHabitsView: to_candid_variant_n26(_uploadFile, _downloadFile, value.defaultHabitsView),
        confirmDelete: value.confirmDelete,
        mondayFirst: value.mondayFirst
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_ontime_late_failed): {
    ontime: null;
} | {
    late: null;
} | {
    failed: null;
} {
    return value == Variant_ontime_late_failed.ontime ? {
        ontime: null
    } : value == Variant_ontime_late_failed.late ? {
        late: null
    } : value == Variant_ontime_late_failed.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_monthly_daily_weekly): {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == Variant_monthly_daily_weekly.monthly ? {
        monthly: null
    } : value == Variant_monthly_daily_weekly.daily ? {
        daily: null
    } : value == Variant_monthly_daily_weekly.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_timer_normal): {
    timer: null;
} | {
    normal: null;
} {
    return value == Variant_timer_normal.timer ? {
        timer: null
    } : value == Variant_timer_normal.normal ? {
        normal: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_onetime_daily): {
    onetime: null;
} | {
    daily: null;
} {
    return value == Variant_onetime_daily.onetime ? {
        onetime: null
    } : value == Variant_onetime_daily.daily ? {
        daily: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "day";
    day: string;
} | {
    __kind__: "month";
    month: string;
} | {
    __kind__: "week";
    week: string;
} | {
    __kind__: "alltime";
    alltime: null;
}): {
    day: string;
} | {
    month: string;
} | {
    week: string;
} | {
    alltime: null;
} {
    return value.__kind__ === "day" ? {
        day: value.day
    } : value.__kind__ === "month" ? {
        month: value.month
    } : value.__kind__ === "week" ? {
        week: value.week
    } : value.__kind__ === "alltime" ? {
        alltime: value.alltime
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
